name: Deploy Website baru

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy website_baru to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USER_SERVER }}
          key: ${{ secrets.PRIVATE_KEY_SERVER }}
          port: 777
          script: |
            cd /var/www/website_baru
            git fetch origin 
            git reset --hard origin/main 
            sudo systemctl restart nginx